FROM node:20-alpine
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN corepack enable && pnpm install --frozen-lockfile
COPY apps/api ./apps/api
WORKDIR /app/apps/api
EXPOSE 8080
CMD ["pnpm","dev"]
